### ISSUE TITLE
"Error 133 occurred" when try to connect to the beacon

### ISSUE THREAD

**Issue by laurijamsa** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#1]
When using Samsung Galaxy S7 Edge, error 133 shows up every time. Galaxy S5 connects successfully sometimes, but not always. This happens with your HEX file: https://github.com/NordicSemiconductor/nrf5-sdk-for-eddystone/blob/master/hex/nrf5_sdk_for_eddystone_v0.5.hex

I get the same result with both HWs: PCA10040 and our open-source sensor beacon platform: http://ruuvitag.com

**Comment by roshanrajaratnam** [comment]
Hi we will try to look in to this tomorrow. Have you tried turning on/off your Bluetooth on the edge?

**Comment by laurijamsa** [comment]
Yes I have. No help.

**Comment by roshanrajaratnam** [comment]
@laurijamsa currently im testing with a Galaxy S7 and it seems to keep happening too often on samsung s7 particularly. S5 seems to be much better on establishing the connection. However this is not the case with Nexus devices. I will debug more and get back to you on this.

**Comment by laurijamsa** [comment]
Please also note that I was having similar problems (GATT error if I recall correctly) with nRF Toolbox (DFU OTA) & S7 Edge. S5 is working fine. DFU OTA is working with S7 Edge + Master Control Panel, but not with Toolbox.

I didn't create an issue (yet) but I can create one if you ask me to. Seems that there are some unresolved ones (why's that?), but no new ones: https://github.com/NordicSemiconductor/Android-nRF-Toolbox/issues

**Comment by roshanrajaratnam** [comment]
yeah we had done a lot of digging on this and the only reason we could come up with is that this is an issue related to the android bluetooth stack since 4.3. I've just looked it up and there is an issue on the [android](https://code.google.com/p/android/issues/detail?id=58381) but is a very Generic error with very little explanation as to what the real cause is.

But there is another work around if it helps you and that would be go to in to application manager >> >> Bluetooth share (if not visible enable show system apps from the options menu) >> and clear data and this should help you to connect to the beacon as this just worked for me.

**Comment by roshanrajaratnam** [comment]
@laurijamsa have you had any success with this issue?

**Comment by laurijamsa** [comment]
@roshanrajaratnam Now I have connected successfully using S7 Edge. However, it still fails almost every time.

BTW, not sure if the parameters should be configurable already or is it TBD? If I modify a Tx power for example, it doesn't save the new value. And URL is static. Why is this?

**Comment by roshanrajaratnam** [comment]
@laurijamsa I am currently looking more in to the 133 error. Parameters are configurable except for the advanced characteristics as they are not supported in the firmware yet. 

The Tx power is configurable and if you look in to broadcast capabilities it lists the tx powers that are supported by the firmware. it is configurable with the values listed there....but it's my bad and there will be a new feature release pretty soon with a drop down so that it lists the supported tx powers in a dropdown menu to be configured. :)

What do you mean by the URL is static? you can configure any slot in to any frametype you wish. In case you want to configure it in to a URL beacon simply pick the url frame type from the dropdown. You can put in your own url which should be less than 18 bytes and if not you can use the shorten url feature to put in a shortened URL.

**Comment by laurijamsa** [comment]
Oh, I just didn't know how to use the app correctly. The URL modification seems to work without problems. Good work! 
![its-alive](https://cloud.githubusercontent.com/assets/1311912/14670287/a106111a-0716-11e6-98a9-75174d898fee.jpg)

**Comment by roshanrajaratnam** [comment]
that sounds good! :) and that's a cool beacon!

**Comment by laurijamsa** [comment]
Thanks! We are working hard to make it available soon :)
![coming-soon-to-kickstarter](https://cloud.githubusercontent.com/assets/1311912/14670722/7de567ec-0718-11e6-97c5-c254f7ea4588.jpg)

**Comment by laurijamsa** [comment]
I made some tests with the new hex file you released an hour ago:

https://github.com/NordicSemiconductor/nrf5-sdk-for-eddystone/blob/master/hex/nrf5_sdk_for_eddystone_v0.6.hex

and so far haven't seen **Error 133** with S7 Edge. Connects every time. Nice!

**Comment by roshanrajaratnam** [comment]
This is good news! we have added a line to update the connection parameters so the android device will try to fit in to the connection parameters of the firmware application. This was something happening mainly on Samsung devices so I guess I will close this issue and on a separate note I would like to have a play around with your ruuvitag if possible.
