### ISSUE TITLE
register beacon (EID) return 403, permission_denied error

### ISSUE THREAD

**Issue by vnarendra5a1** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#5]
I configured my G Dev console:
1) enabled proximity API
2) added credentials for OAuth2.0 and Client ID. Based on the SHA1 code of my machine.

I used the same SHA1 for debugging my app from android studio.

**Comment by roshanrajaratnam** [comment]
@vnarendra5a1  sorry for the delayed reply on this issue. I have fixed this issue and let me know how it goes for you. This was basically due to the introduction of Project Delegation where users have to have write access to a Console Project as an Owner or an Editor. If you do not have a project with write access the Proximity API will not let you register beacons. I have included some resources on the read me section. let me know how it goes.

**Comment by roshanrajaratnam** [comment]
@vnarendra5a1  Since there is no reply on this issue I will close this issue now.
